name: app_clima
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations: 
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.5
  provider:
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  go_router: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

 
